table dim_fiscal_calendar
	lineageTag: 76656e50-01b6-45fa-856e-64d524755802
	dataCategory: Time

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a453fc30-4976-4729-8488-c050692357b2
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column first_day_of_month
		dataType: dateTime
		formatString: Long Date
		lineageTag: cc7c1092-878a-42db-bd6d-d17fc8ab141c
		summarizeBy: none
		sourceColumn: first_day_of_month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: cbf1f477-6846-47fd-9428-1078bcfa11a5
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: fa44b383-cddc-472c-a5fa-6877a43f9ac6
		summarizeBy: sum
		sourceColumn: month_number

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: fa3e6c9b-2f00-4e5a-b898-f982471043e4
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: string
		lineageTag: e34dee57-d9bd-4f8e-aa41-ad942337b725
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		formatString: Long Date
		lineageTag: 0f127bd4-57a7-4d8d-b6d5-44b24a5c13e9
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition dim_fiscal_calendar = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("C:\Users\Ary Palacios\Desktop\corporate-fpa-project\Data\exports\dim_fiscal_calendar.csv"), [Delimiter = ",", Columns = 7, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"date", type date}, {"first_day_of_month", type date}, {"year", Int64.Type}, {"month_number", Int64.Type}, {"month_name", type text}, {"quarter", type text}, {"year_month", type text}}, "es")
				in
				  #"Tipo de columna cambiado"

	annotation PBI_ResultType = Table

