table fct_sales_subledger
	lineageTag: d88ebe57-7eb2-4fc2-89c8-5a044b17b371

	column transaction_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ea9b1acf-d726-415d-b32f-afa4bfa2402f
		summarizeBy: none
		sourceColumn: transaction_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column entity_id
		dataType: int64
		formatString: 0
		lineageTag: 75845909-c53b-451b-a1e5-0cbd231a0306
		summarizeBy: none
		sourceColumn: entity_id

		annotation SummarizationSetBy = Automatic

	column sku_id
		dataType: int64
		formatString: 0
		lineageTag: 38fb28d1-8b3e-46a0-82a8-b3734adfb997
		summarizeBy: none
		sourceColumn: sku_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: b830702e-8dc7-49c9-afe9-272ca6a52a08
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column units_sold
		dataType: int64
		formatString: 0
		lineageTag: 9ef080ba-c784-4145-a42d-8808f15bc1cd
		summarizeBy: sum
		sourceColumn: units_sold

		annotation SummarizationSetBy = Automatic

	column actual_unit_price
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$0.00
		lineageTag: dc5983a7-c7f5-4e7c-8c82-f2cea4c19d26
		summarizeBy: sum
		sourceColumn: actual_unit_price

		annotation SummarizationSetBy = Automatic

	column budget_unit_price
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$0.00
		lineageTag: 85a16d61-a94e-484f-a14d-16806c59d17c
		summarizeBy: sum
		sourceColumn: budget_unit_price

		annotation SummarizationSetBy = Automatic

	column budget_units
		dataType: int64
		formatString: 0
		lineageTag: 88054a37-d509-4a7e-ba9c-2a0ea833931f
		summarizeBy: sum
		sourceColumn: budget_units

		annotation SummarizationSetBy = Automatic

	partition fct_sales_subledger = m
		mode: import
		source =
				let
				  Origen = Csv.Document(File.Contents("C:\Users\Ary Palacios\Desktop\corporate-fpa-project\Data\exports\fct_sales_subledger.csv"), [Delimiter = ",", Columns = 8, QuoteStyle = QuoteStyle.None]),
				  #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				  #"Tipo de columna cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos", {{"transaction_date", type date}, {"entity_id", Int64.Type}, {"sku_id", Int64.Type}, {"product_name", type text}, {"units_sold", Int64.Type}, {"actual_unit_price", type number}, {"budget_unit_price", type number}, {"budget_units", Int64.Type}}, "en-US")
				in
				  #"Tipo de columna cambiado"

	annotation PBI_ResultType = Table

